# Generated by Django 4.1.6 on 2023-03-09 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applytrackerapi', '0003_rename_eventattendance_attendance_event_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover_Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter_url', models.URLField(max_length=300, null=True)),
                ('name', models.CharField(max_length=155)),
                ('finalized', models.BooleanField(null=True)),
                ('body', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('job_post_link', models.URLField(max_length=2048, null=True)),
                ('applied', models.BooleanField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('description', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cover_letter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_letter_jobs', to='applytrackerapi.cover_letter')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_url', models.URLField(max_length=300, null=True)),
                ('resume_name', models.CharField(max_length=155)),
                ('date_reviewed', models.DateField(null=True)),
                ('body', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_job', to='applytrackerapi.job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_service_jobs', to='applytrackerapi.job_service'),
        ),
        migrations.AddField(
            model_name='job',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_resume', to='applytrackerapi.resume'),
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_jobs', to='applytrackerapi.role'),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_name', models.CharField(max_length=155)),
                ('interviewer_email', models.CharField(max_length=155)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('location', models.CharField(max_length=400, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_interview', to='applytrackerapi.job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cover_letter',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_cover_letter', to='applytrackerapi.job'),
        ),
        migrations.AddField(
            model_name='cover_letter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('job', models.ManyToManyField(to='applytrackerapi.job')),
            ],
        ),
    ]
