# Generated by Django 4.1.6 on 2023-03-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applytrackerapi', '0006_alter_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
