# Generated by Django 4.1.6 on 2023-03-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applytrackerapi', '0008_alter_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applied',
            field=models.DateField(null=True),
        ),
    ]
