# Generated by Django 4.1.6 on 2023-03-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applytrackerapi', '0010_remove_interview_interviewer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
    ]
