# Generated by Django 4.1.6 on 2023-03-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applytrackerapi', '0011_job_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applytrackerapi.role'),
        ),
    ]
