# Generated by Django 4.1.6 on 2023-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applytrackerapi', '0016_job_service_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='job',
            field=models.ManyToManyField(blank=True, to='applytrackerapi.job'),
        ),
    ]
