# Generated by Django 4.1.6 on 2023-03-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applytrackerapi', '0017_alter_company_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job',
        ),
        migrations.AddField(
            model_name='company',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_company', to='applytrackerapi.job'),
        ),
    ]
