# Generated by Django 4.1.6 on 2023-03-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applytrackerapi', '0018_remove_company_job_company_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job',
        ),
        migrations.AddField(
            model_name='company',
            name='job',
            field=models.ManyToManyField(blank=True, related_name='job_company', to='applytrackerapi.job'),
        ),
    ]
