# Generated by Django 4.1.6 on 2023-03-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applytrackerapi', '0020_remove_company_job_remove_job_companyjobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='contact',
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewcontacts',
            field=models.ManyToManyField(through='applytrackerapi.InterviewAttendance', to='applytrackerapi.contact'),
        ),
    ]
