# Generated by Django 4.1.6 on 2023-03-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applytrackerapi', '0022_alter_interview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='game',
        ),
        migrations.RemoveField(
            model_name='event',
            name='gamer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='game',
            name='gamer',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Gamer',
        ),
        migrations.DeleteModel(
            name='GameType',
        ),
    ]
